/**
* sdk.proto
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: version not set
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package io.github.kunjakob.agonesclient.models

import io.github.kunjakob.agonesclient.models.StatusPlayerStatus
import io.github.kunjakob.agonesclient.models.StatusPort

import com.squareup.moshi.Json
/**
 * 
 * @param state 
 * @param address 
 * @param ports 
 * @param players 
 */

data class GameServerStatus (
    @Json(name = "state")
    var state: kotlin.String? = null,
    @Json(name = "address")
    var address: kotlin.String? = null,
    @Json(name = "ports")
    var ports: kotlin.Array<StatusPort>? = null,
    @Json(name = "players")
    var players: StatusPlayerStatus? = null
)

