/**
* sdk.proto
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: version not set
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package io.github.kunjakob.agonesclient.models


import com.squareup.moshi.Json
/**
 * 
 * @param name 
 * @param namespace 
 * @param uid 
 * @param resourceVersion 
 * @param generation 
 * @param creationTimestamp 
 * @param deletionTimestamp 
 * @param annotations 
 * @param labels 
 */

data class GameServerObjectMeta (
    @Json(name = "name")
    var name: kotlin.String? = null,
    @Json(name = "namespace")
    var namespace: kotlin.String? = null,
    @Json(name = "uid")
    var uid: kotlin.String? = null,
    @Json(name = "resource_version")
    var resourceVersion: kotlin.String? = null,
    @Json(name = "generation")
    var generation: kotlin.String? = null,
    @Json(name = "creation_timestamp")
    var creationTimestamp: kotlin.String? = null,
    @Json(name = "deletion_timestamp")
    var deletionTimestamp: kotlin.String? = null,
    @Json(name = "annotations")
    var annotations: kotlin.collections.Map<kotlin.String, kotlin.String>? = null,
    @Json(name = "labels")
    var labels: kotlin.collections.Map<kotlin.String, kotlin.String>? = null
)

