/**
* sdk.proto
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: version not set
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package io.github.kunjakob.agonesclient.models

import io.github.kunjakob.agonesclient.models.SpecHealth

import com.squareup.moshi.Json
/**
 * 
 * @param health 
 */

data class GameServerSpec (
    @Json(name = "health")
    var health: SpecHealth? = null
)

