/**
* sdk.proto
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: version not set
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package io.github.kunjakob.agonesclient.models


import com.squareup.moshi.Json
/**
 * 
 * @param typeUrl 
 * @param value 
 */

data class ProtobufAny (
    @Json(name = "type_url")
    var typeUrl: kotlin.String? = null,
    @Json(name = "value")
    var value: kotlin.ByteArray? = null
)

