/**
* sdk.proto
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: version not set
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package io.github.kunjakob.agonesclient.models

import io.github.kunjakob.agonesclient.models.ProtobufAny

import com.squareup.moshi.Json
/**
 * 
 * @param grpcCode 
 * @param httpCode 
 * @param message 
 * @param httpStatus 
 * @param details 
 */

data class RuntimeStreamError (
    @Json(name = "grpc_code")
    var grpcCode: kotlin.Int? = null,
    @Json(name = "http_code")
    var httpCode: kotlin.Int? = null,
    @Json(name = "message")
    var message: kotlin.String? = null,
    @Json(name = "http_status")
    var httpStatus: kotlin.String? = null,
    @Json(name = "details")
    var details: kotlin.Array<ProtobufAny>? = null
)

