/**
* sdk.proto
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: version not set
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package io.github.kunjakob.agonesclient.models


import com.squareup.moshi.Json
/**
 * 
 * @param disabled 
 * @param periodSeconds 
 * @param failureThreshold 
 * @param initialDelaySeconds 
 */

data class SpecHealth (
    @Json(name = "disabled")
    var disabled: kotlin.Boolean? = null,
    @Json(name = "period_seconds")
    var periodSeconds: kotlin.Int? = null,
    @Json(name = "failure_threshold")
    var failureThreshold: kotlin.Int? = null,
    @Json(name = "initial_delay_seconds")
    var initialDelaySeconds: kotlin.Int? = null
)

