/**
* sdk.proto
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: version not set
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package io.github.kunjakob.agonesclient.models


import com.squareup.moshi.Json
/**
 * 
 * @param count 
 * @param capacity 
 * @param ids 
 */

data class StatusPlayerStatus (
    @Json(name = "count")
    var count: kotlin.String? = null,
    @Json(name = "capacity")
    var capacity: kotlin.String? = null,
    @Json(name = "ids")
    var ids: kotlin.Array<kotlin.String>? = null
)

